-- =====================================================================
-- Every migration, concatenated, for pasting into the Supabase SQL editor.
--
-- This file exists for one situation: a hosted project the CLI cannot link
-- to. The supported path is `supabase db push`, which keeps a migration
-- history table so the next migration knows what already ran. Pasting this
-- does NOT record that history, so after running it once, either link the
-- project and `supabase migration repair --status applied 0001 ... 0006`, or
-- keep applying future changes by hand.
--
-- Everything here is idempotent: `if not exists`, `create or replace`, and
-- `drop policy if exists` before each `create policy`. Running it twice is
-- safe. Running it against a database that already has data is safe; it
-- creates and replaces, it never drops a table.
--
-- Generated by scripts, do not hand-edit. Source of truth is
-- supabase/migrations/.
-- =====================================================================











-- ============ 0001_core_tables.sql ============

-- 0001_core_tables.sql
--
-- The multi-tenant core of the resume-tailoring platform.
--
-- This replaces backend/src/atsresume/store.py, which was a three-table SQLite
-- file with no notion of a user. Two things from that file survive as ideas and
-- are worth restating, because they are why several columns here exist:
--
--   * FINGERPRINTING. store.py keyed cached facts on
--     sha256(extracted_text) + a hash of the extraction prompt and the
--     ResumeFacts JSON schema. Re-extracting a resume costs a model call and
--     several seconds, and the same bytes always produce the same facts *for a
--     given extraction contract*. The contract hash is what makes the cache
--     safe to keep: change the prompt or the schema and every old key misses
--     instead of serving stale shapes. That idea lives on in two places here:
--     `documents.sha256` / `jobs.sha256` (content identity) and
--     `step_cache.cache_key` + `step_cache.prompt_version` (contract identity).
--
--   * THE FACTS CACHE. It existed so a user could re-tailor against a second
--     job without paying for extraction twice. Here it is no longer a cache at
--     all: `facts` is a durable, append-only provenance ledger, because the
--     truth guard needs to answer "which line of which document does this
--     claim come from" long after the upload is gone.
--
-- Conventions
--   * Every user-scoped table carries `user_id uuid not null references
--     auth.users(id) on delete cascade`. Denormalised onto every table on
--     purpose: an RLS policy that has to join upward to find the owner is both
--     slower and easier to get wrong than one that reads a local column.
--   * Timestamps are timestamptz, defaulted to now().
--   * Structured payloads are jsonb and mirror the Pydantic models in
--     backend/src/atsresume/models.py one-for-one. Which model belongs in which
--     column is stated on the column.
--   * ids are uuid defaulted from gen_random_uuid(), so a client can mint an id
--     before the round trip.

create extension if not exists pgcrypto;

-- --------------------------------------------------------------------------
-- documents — the uploaded artefact, exactly as it arrived
-- --------------------------------------------------------------------------
-- One row per upload, mirroring models.SourceDocument. The bytes themselves
-- live in Storage (see 0006_storage.sql); `storage_path` points at them and is
-- always prefixed with the owner's uid, which is what the Storage policies
-- key on.
--
-- DECISION: raw_text is stored here and not only in Storage. The truth guard
-- re-reads the original text on every tailor run to verify that a rewritten
-- line is entailed by something the candidate actually wrote. Making that a
-- Storage fetch would put a network call in the middle of a hot verification
-- loop, and would break entirely once the user deletes the file but keeps the
-- resume built from it.
create table if not exists documents (
    id           uuid primary key default gen_random_uuid(),
    user_id      uuid not null references auth.users (id) on delete cascade,
    storage_path text,                       -- '<uid>/<document_id>.pdf' in the 'resumes' bucket; null for pasted text
    kind         text not null check (kind in ('pdf', 'docx', 'text')),
    sha256       text,                       -- of the extracted text, not the file bytes
    page_count   int  not null default 0,
    style_json   jsonb,                      -- models.StyleProfile; null for docx/text
    raw_text     text not null default '',
    notes        jsonb not null default '[]'::jsonb,  -- SourceDocument.notes, a string array
    created_at   timestamptz not null default now()
);

comment on column documents.sha256 is
    'sha256 of the normalised extracted text. Content identity, not file identity: '
    'the same resume exported twice from Word produces different bytes but the same text.';

-- Re-uploading the same resume should land on the same row rather than
-- fanning out duplicate facts. Partial, because a pasted document may not
-- have been hashed.
create unique index if not exists documents_user_sha256_key
    on documents (user_id, sha256)
    where sha256 is not null;

-- --------------------------------------------------------------------------
-- facts — the provenance ledger. APPEND-ONLY.
-- --------------------------------------------------------------------------
-- Flattened from models.ResumeFacts: every Bullet, SkillGroup, Certification
-- and OtherSection line becomes one row, addressed by the stable id the
-- extractor assigns ('E1.B2', 'P1', 'S3'). models.py puts it plainly: the
-- facts are what the candidate claimed, and tailored lines cite them by id.
-- That citation is only verifiable if the cited row still exists and still
-- says what it said when it was cited. Hence append-only.
--
-- DECISION — deleting a document must not delete its facts.
--   `document_id ... on delete set null`. A user who deletes an upload is
--   deleting a file, not retracting a claim: resumes already tailored from it
--   still cite these fact_keys, and the truth guard would start failing rows
--   it previously passed. `evidence_json` snapshots the supporting span from
--   the source text at insert time, so a fact stays self-describing after its
--   document is gone. If the user really means "forget this", that is an
--   account- or document-level erasure job that tombstones the facts too, and
--   it is deliberately a different, louder operation.
--
-- DECISION — ship `origin` now.
--   Attestation ("I confirm I did this, it just wasn't on the resume") is a
--   later phase. The column is here anyway because provenance cannot be
--   backfilled: once a few thousand rows exist with no origin recorded, there
--   is no way to tell a document-extracted fact from a user-attested one
--   except by guessing, and guessing about provenance is exactly the failure
--   the truth guard exists to prevent.
--     'document'  — extracted verbatim from an uploaded document
--     'attested'  — asserted by the user in chat, never seen in a document
--     'derived'   — computed from other facts (e.g. total years from dates)
create table if not exists facts (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null references auth.users (id) on delete cascade,
    document_id   uuid references documents (id) on delete set null,
    fact_key      text not null,             -- 'E1', 'E1.B2', 'P1', 'S2', 'C1', 'O1.B1'
    text          text not null,             -- verbatim; never paraphrased
    origin        text not null default 'document'
                  check (origin in ('document', 'attested', 'derived')),
    -- What the truth guard tokenises against, extracted once at insert:
    --   {"metrics":["40%","1.2M"],"technologies":["Postgres","FastAPI"],
    --    "employers":["Acme"],"dates":["Jun 2023"]}
    entities_json jsonb not null default '{}'::jsonb,
    -- Where it came from: {"page":1,"char_start":812,"char_end":902,
    --                      "quote":"…","section":"experience"}
    evidence_json jsonb not null default '{}'::jsonb,
    supersedes    uuid references facts (id) on delete set null,
    valid_from    timestamptz not null default now(),
    valid_to      timestamptz,               -- null = currently believed
    created_at    timestamptz not null default now()
);

comment on table facts is
    'Append-only provenance ledger. Correct a fact by inserting a new row whose '
    'supersedes points at the old one; the trigger in 0005 closes the old row''s '
    'valid_to and rejects any other mutation.';

-- A fact may only be superseded once, otherwise "the current version of E1.B2"
-- has two answers and the guard cannot pick one.
create unique index if not exists facts_supersedes_key
    on facts (supersedes)
    where supersedes is not null;

-- --------------------------------------------------------------------------
-- jobs — the JD, raw and decomposed
-- --------------------------------------------------------------------------
-- Declared before `resumes` because resumes.job_id references it.
create table if not exists jobs (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null references auth.users (id) on delete cascade,
    source_url text,
    jd_text    text not null default '',
    jd_source  text not null default '',     -- 'pasted', 'greenhouse', 'lever', …
    company    text not null default '',     -- denormalised from spec_json for list views
    title      text not null default '',
    spec_json  jsonb,                        -- models.JobSpec; null until extraction runs
    sha256     text,                         -- of the normalised jd_text
    created_at timestamptz not null default now()
);

-- Same JD pasted twice by the same user is the same job. Cross-user dedupe is
-- deliberately NOT done here: two tenants must never share a row, even for
-- identical public text. Sharing the *derived extraction* is what step_cache is
-- for, and that is safe precisely because a JD is not personal data.
create unique index if not exists jobs_user_sha256_key
    on jobs (user_id, sha256)
    where sha256 is not null;

-- --------------------------------------------------------------------------
-- resumes — a named, editable document the user owns
-- --------------------------------------------------------------------------
-- The mutable head. Content lives in resume_versions; this row holds identity,
-- and a cached pointer at the newest version.
--
-- DECISION — can current_version_id dangle?
--   No, and it is the schema that guarantees it rather than the application:
--     * resume_versions carries `unique (id, resume_id)`, and resumes has a
--       COMPOSITE foreign key (current_version_id, id) -> (id, resume_id).
--       A resume therefore cannot point at another resume's version. A plain
--       single-column FK would have allowed exactly that.
--     * `on delete set null (current_version_id)` — PG 15+ column-list syntax,
--       available on Supabase — so deleting the pointed-at version nulls the
--       pointer instead of erroring or cascading the whole resume away. The
--       trigger in 0005 then re-points it at whatever version is now newest.
--   Null is a legal state: a resume that exists but has no version yet.
create table if not exists resumes (
    id                 uuid primary key default gen_random_uuid(),
    user_id            uuid not null references auth.users (id) on delete cascade,
    title              text not null default 'Untitled resume',
    template_id        text not null default 'default',
    -- 'Tailor a copy for this job' — the lineage back to the master resume.
    -- set null, not cascade: deleting the master must not delete the tailored
    -- children the user actually sent to employers.
    base_resume_id     uuid references resumes (id) on delete set null,
    job_id             uuid references jobs (id) on delete set null,
    schema_version     int  not null default 1,   -- doc_json shape; bump on breaking change
    current_version_id uuid,                      -- composite FK added below
    status             text not null default 'draft',
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);

comment on column resumes.status is
    'Application state: draft, applied, screening, interviewing, offer, rejected, '
    'abandoned. Free text, as in store.py, so a new state needs no migration.';

comment on column resumes.schema_version is
    'Version of the doc_json shape in resume_versions. A reader that finds a '
    'schema_version it does not know must refuse to render rather than guess.';

-- --------------------------------------------------------------------------
-- resume_versions — immutable content snapshots
-- --------------------------------------------------------------------------
-- Every save is a new row. `parent_id` makes the history a tree rather than a
-- list, which is what lets an accepted patch branch from an older version
-- without destroying what came after.
create table if not exists resume_versions (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null references auth.users (id) on delete cascade,
    resume_id  uuid not null references resumes (id) on delete cascade,
    parent_id  uuid references resume_versions (id) on delete set null,
    -- models.TailoredResume, plus contact taken from ResumeFacts. The whole
    -- renderable document, self-contained: rendering an old version must not
    -- depend on today's facts rows.
    doc_json   jsonb not null,
    created_by text not null
               check (created_by in ('ai_tailor', 'ai_chat', 'user', 'import')),
    created_at timestamptz not null default now(),
    -- Target of the composite FK from resumes.current_version_id.
    unique (id, resume_id)
);

alter table resumes
    drop constraint if exists resumes_current_version_fkey;
alter table resumes
    add constraint resumes_current_version_fkey
    foreign key (current_version_id, id)
    references resume_versions (id, resume_id)
    on delete set null (current_version_id)
    deferrable initially deferred;
-- DEFERRABLE because the natural write is "insert version, then point the
-- resume at it" inside one transaction; with an immediate constraint the
-- application would have to order those two statements correctly forever.

-- --------------------------------------------------------------------------
-- patches — proposed edits, as ops rather than as text
-- --------------------------------------------------------------------------
-- The AI proposes a patch against a specific base version; the user accepts or
-- declines. Storing ops (RFC-6902-shaped paths into doc_json) rather than a
-- rewritten document is what makes "accept just this one bullet" possible and
-- what makes the diff reviewable.
--
-- DECISION — can a patch be accepted twice?
--   No. 'proposed' is the only non-terminal status; the trigger in 0005
--   rejects any transition out of accepted/declined/superseded, and stamps
--   decided_at. Without that, a double-click on Accept applies the same ops
--   twice and silently duplicates a bullet. `applied_version_id` records which
--   version the acceptance produced, so the answer to "was this already
--   applied, and where" is a column rather than an inference.
create table if not exists patches (
    id                 uuid primary key default gen_random_uuid(),
    user_id            uuid not null references auth.users (id) on delete cascade,
    resume_id          uuid not null references resumes (id) on delete cascade,
    base_version_id    uuid not null references resume_versions (id) on delete cascade,
    -- [{"op":"replace","path":"/experience/0/bullets/1/text","value":"…",
    --   "source_ids":["E1.B2"]}, …]
    ops_json           jsonb not null,
    origin             text not null default 'ai_tailor',   -- ai_tailor | ai_chat | user
    status             text not null default 'proposed'
                       check (status in ('proposed', 'accepted', 'declined', 'superseded')),
    rationale          text not null default '',
    score_delta        numeric,              -- predicted change in AtsReport.overall
    applied_version_id uuid references resume_versions (id) on delete set null,
    decided_at         timestamptz,
    created_at         timestamptz not null default now(),
    -- A decision must be recorded when and only when one was made.
    constraint patches_decided_at_matches_status check (
        (status = 'proposed' and decided_at is null)
        or (status <> 'proposed' and decided_at is not null)
    ),
    -- Only an accepted patch can have produced a version.
    constraint patches_applied_only_when_accepted check (
        applied_version_id is null or status = 'accepted'
    )
);

-- --------------------------------------------------------------------------
-- resume_jobs — one resume measured against one job
-- --------------------------------------------------------------------------
-- The analysis layer, kept out of both parents because it belongs to neither:
-- re-running the gap analysis must not create a new resume version, and
-- re-scoring against a second job must not touch the first job's report.
create table if not exists resume_jobs (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references auth.users (id) on delete cascade,
    resume_id   uuid not null references resumes (id) on delete cascade,
    job_id      uuid not null references jobs (id) on delete cascade,
    gaps_json   jsonb,                       -- models.GapAnalysis
    report_json jsonb,                       -- models.AtsReport
    truth_json  jsonb,                       -- models.TruthReport
    strategy_json jsonb,                     -- models.Strategy
    created_at  timestamptz not null default now(),
    unique (resume_id, job_id)
);

-- --------------------------------------------------------------------------
-- chat_sessions / chat_messages
-- --------------------------------------------------------------------------
create table if not exists chat_sessions (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null references auth.users (id) on delete cascade,
    resume_id  uuid not null references resumes (id) on delete cascade,
    kind       text not null check (kind in ('edit', 'interview')),
    created_at timestamptz not null default now()
);

create table if not exists chat_messages (
    id              uuid primary key default gen_random_uuid(),
    user_id         uuid not null references auth.users (id) on delete cascade,
    session_id      uuid not null references chat_sessions (id) on delete cascade,
    role            text not null check (role in ('user', 'assistant', 'system', 'tool')),
    content         text not null default '',
    tool_calls_json jsonb,
    tokens_in       int not null default 0,
    tokens_out      int not null default 0,
    cost_usd        numeric(12, 6) not null default 0,
    created_at      timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- step_cache — content-addressed, DELIBERATELY NOT USER-SCOPED
-- --------------------------------------------------------------------------
-- Every other table in this file is a tenant's private data. This one is not,
-- and the asymmetry is intentional, so read the rule before adding a caller.
--
-- WHY IT IS GLOBAL
--   Pipeline steps are pure functions of their input. Extracting a JobSpec
--   from a Greenhouse posting costs a model call and several seconds, and two
--   candidates applying to the same job paste byte-identical text. Keying the
--   cache by a hash of the input rather than by user turns the second
--   candidate's extraction into a lookup. Scoping it per user would throw that
--   away for no benefit, because the output does not depend on who asked.
--
-- THE PRIVACY CONSEQUENCE YOU MUST DESIGN AROUND
--   A content-addressed cache is a read oracle. Anyone able to compute a
--   cache_key can retrieve the value stored under it. If a key were derived
--   from resume text, then a cache hit would (a) hand one tenant a value
--   computed from another tenant's private document, and (b) confirm, by the
--   hit alone, that some other user holds that exact text. Both are tenant
--   leaks, and neither is fixed by RLS on this table: the leak is in the key,
--   not in the row.
--
-- THE RULE  (enforce it in the key-derivation helper, not by inspection)
--   1. GLOBAL KEYS may be derived only from NON-PII inputs: job description
--      text, prompt text, model id, prompt_version, static taxonomies. A JD is
--      published by an employer; it is not the user's personal data.
--   2. ANY step whose input includes resume-derived material — raw_text,
--      ResumeFacts, a tailored document, chat content, anything a user wrote
--      about themselves — MUST include the user_id in the hashed key:
--          cache_key = sha256(step | prompt_version | model | user_id | input)
--      The entry is then content-addressed *within one tenant* and a
--      cross-tenant hit is arithmetically impossible.
--   3. Uncertain which bucket a new step falls in? It is bucket 2. The cost of
--      a wrong guess is a per-user cache miss one way and a data breach the
--      other.
--   4. Nothing derived from a document may be written here in plaintext even
--      under a user-scoped key, if the value itself would be readable by
--      guessing the key. Where a value is sensitive, cache it in the owning
--      table instead — `facts` is the resume-extraction cache, which is why
--      store.py's facts cache is not represented here.
--
-- ACCESS: RLS is enabled with no policy for anon/authenticated (0002), so only
-- the service role — the backend, which derives the keys and can be held to the
-- rule above — can read or write it. No browser ever touches this table.
create table if not exists step_cache (
    cache_key      text primary key,   -- sha256 hex; see the rule above for its inputs
    step           text not null,      -- 'jd_extract', 'gap_analysis', 'tailor', …
    output_json    jsonb not null,
    model          text not null default '',
    prompt_version text not null default '',
    hits           int  not null default 0,
    created_at     timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- step_traces — observability
-- --------------------------------------------------------------------------
-- User-scoped, unlike step_cache, because these rows answer "what did MY run
-- cost and why was it slow" and are shown back to the user.
--
-- resume_id is nullable and `on delete set null`: a JD extraction happens
-- before any resume is chosen, and deleting a resume must not erase the
-- billing record of work already paid for.
create table if not exists step_traces (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null references auth.users (id) on delete cascade,
    resume_id  uuid references resumes (id) on delete set null,
    step       text not null,
    model      text not null default '',
    tokens_in  int  not null default 0,
    tokens_out int  not null default 0,
    ms         int  not null default 0,
    cost_usd   numeric(12, 6) not null default 0,
    ok         boolean not null default true,
    cache_hit  boolean not null default false,
    error      text not null default '',
    created_at timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- storage_gc_queue — the answer to "cascade deletes orphan storage objects"
-- --------------------------------------------------------------------------
-- DECISION. `on delete cascade` from auth.users reaches every row in this
-- schema, but it does NOT reach storage.objects: those are rows in another
-- schema with no FK to documents, and the bytes behind them are in S3. Deleting
-- a user therefore silently leaves their uploaded PDFs on disk forever — a
-- storage bill and, more importantly, a GDPR erasure failure.
--
-- Rather than pretend the database can delete an S3 object, we make the
-- orphan explicit: an AFTER DELETE trigger on `documents` (0005) enqueues the
-- storage_path here, and a scheduled worker running as the service role
-- deletes the object and then the queue row. A queue that is visibly draining
-- is auditable; a cascade that quietly leaks is not.
--
-- Not user-scoped and service-role only: it must survive the deletion of the
-- user whose objects it is about, which is precisely why it has no FK to
-- auth.users.
create table if not exists storage_gc_queue (
    id           bigserial primary key,
    bucket_id    text not null default 'resumes',
    storage_path text not null,
    owner_id     uuid,                       -- plain uuid, no FK: the user may be gone
    enqueued_at  timestamptz not null default now(),
    deleted_at   timestamptz,
    attempts     int not null default 0,
    last_error   text
);


-- ============ 0002_rls.sql ============

-- 0002_rls.sql
--
-- Row Level Security. This file is the entire tenant boundary: there is no
-- other place where "user A cannot see user B's resume" is enforced, and
-- supabase/tests/rls_test.sql exists to prove it still holds.
--
-- Three conventions, each load-bearing:
--
-- 1. `(select auth.uid())` — NEVER bare `auth.uid()`.
--    Wrapped in a scalar subquery the planner treats it as an InitPlan: it is
--    evaluated once per statement and the result is reused for every row.
--    Written bare, it is a volatile-ish function call re-evaluated per row,
--    which on a sequential scan of a large table is the difference between one
--    call and a million. It also lets the planner use the index on user_id
--    instead of filtering after the fact. The two forms are semantically
--    identical; only one of them scales.
--
-- 2. ONE POLICY PER OPERATION, never `for all`.
--    `for all` collapses select/insert/update/delete into a single expression.
--    The day someone needs to loosen SELECT — a share link, a team view, an
--    admin read — they edit that one expression and silently grant the same
--    loosening to DELETE. Four narrow policies make that mistake impossible to
--    make by accident: widening a read requires touching only the read policy.
--
-- 3. `using` vs `with check`.
--    UPDATE policies specify both. `using` decides which rows you may target;
--    `with check` decides what the row may look like afterwards. With only
--    `using`, a user could target their own row and rewrite user_id to someone
--    else's — handing a row to another tenant, or stealing one by writing their
--    own id onto a row they were allowed to see. Every insert/update check
--    below therefore pins user_id to the caller.
--
-- Roles: `anon` gets nothing anywhere. `authenticated` gets exactly what these
-- policies allow. `service_role` bypasses RLS entirely (BYPASSRLS), which is
-- how the backend does cross-tenant work such as cache maintenance — so any
-- code path running as service_role is outside this boundary and must apply
-- its own filtering.

-- --------------------------------------------------------------------------
-- Grants
-- --------------------------------------------------------------------------
-- RLS narrows privileges, it does not confer them; a table with a permissive
-- policy and no GRANT is still unreadable. Supabase's default privileges
-- usually cover this, but stating it here keeps the migration self-contained
-- and reproducible on a plain Postgres.
grant usage on schema public to anon, authenticated, service_role;

do $$
declare
    t text;
begin
    foreach t in array array[
        'documents', 'facts', 'jobs', 'resumes', 'resume_versions',
        'patches', 'resume_jobs', 'chat_sessions', 'chat_messages', 'step_traces'
    ]
    loop
        execute format(
            'grant select, insert, update, delete on table public.%I to authenticated', t);
        execute format('grant all on table public.%I to service_role', t);
    end loop;
end $$;

-- step_cache and storage_gc_queue get NO grant to anon or authenticated. They
-- are backend-only infrastructure; see the rationale at the bottom of this file.
grant all on table public.step_cache to service_role;
grant all on table public.storage_gc_queue to service_role;
grant usage, select on sequence public.storage_gc_queue_id_seq to service_role;

-- --------------------------------------------------------------------------
-- Enable RLS everywhere
-- --------------------------------------------------------------------------
-- Note `force row level security` as well as `enable`: without FORCE, the
-- table owner bypasses its own policies. In production that is the migration
-- role rather than the request role, but FORCE removes the class of bug where
-- something happens to connect as the owner and quietly sees everything.
do $$
declare
    t text;
begin
    foreach t in array array[
        'documents', 'facts', 'jobs', 'resumes', 'resume_versions',
        'patches', 'resume_jobs', 'chat_sessions', 'chat_messages',
        'step_traces', 'step_cache', 'storage_gc_queue'
    ]
    loop
        execute format('alter table public.%I enable row level security', t);
        execute format('alter table public.%I force row level security', t);
    end loop;
end $$;

-- --------------------------------------------------------------------------
-- documents
-- --------------------------------------------------------------------------
drop policy if exists documents_select_own on documents;
create policy documents_select_own on documents
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists documents_insert_own on documents;
create policy documents_insert_own on documents
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists documents_update_own on documents;
create policy documents_update_own on documents
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists documents_delete_own on documents;
create policy documents_delete_own on documents
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- facts — SELECT and INSERT only, plus a narrow UPDATE
-- --------------------------------------------------------------------------
-- The ledger is append-only, and the cheapest way to enforce that is to not
-- write the policies that would permit otherwise. There is deliberately NO
-- delete policy: a fact cited by a rendered resume must not be able to vanish.
--
-- The UPDATE policy exists for exactly one operation — closing `valid_to` when
-- a newer fact supersedes this one. A policy cannot express "only this column
-- may change", so the column-level restriction is a trigger
-- (facts_append_only_guard, 0005). Policy and trigger are complementary: the
-- policy says whose rows, the trigger says which columns.
drop policy if exists facts_select_own on facts;
create policy facts_select_own on facts
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists facts_insert_own on facts;
create policy facts_insert_own on facts
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists facts_retire_own on facts;
create policy facts_retire_own on facts
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

-- (no facts_delete policy — intentional)

-- --------------------------------------------------------------------------
-- jobs
-- --------------------------------------------------------------------------
drop policy if exists jobs_select_own on jobs;
create policy jobs_select_own on jobs
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists jobs_insert_own on jobs;
create policy jobs_insert_own on jobs
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists jobs_update_own on jobs;
create policy jobs_update_own on jobs
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists jobs_delete_own on jobs;
create policy jobs_delete_own on jobs
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- resumes
-- --------------------------------------------------------------------------
drop policy if exists resumes_select_own on resumes;
create policy resumes_select_own on resumes
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists resumes_insert_own on resumes;
create policy resumes_insert_own on resumes
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists resumes_update_own on resumes;
create policy resumes_update_own on resumes
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists resumes_delete_own on resumes;
create policy resumes_delete_own on resumes
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- resume_versions
-- --------------------------------------------------------------------------
-- Versions are immutable snapshots, so there is no update policy: editing a
-- version in place would rewrite history that patches and renders point at.
-- A correction is a new version with parent_id set. DELETE is allowed because
-- pruning old drafts is a legitimate user action, and the composite FK plus
-- the 0005 trigger keep resumes.current_version_id honest when it happens.
drop policy if exists resume_versions_select_own on resume_versions;
create policy resume_versions_select_own on resume_versions
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists resume_versions_insert_own on resume_versions;
create policy resume_versions_insert_own on resume_versions
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists resume_versions_delete_own on resume_versions;
create policy resume_versions_delete_own on resume_versions
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- patches
-- --------------------------------------------------------------------------
drop policy if exists patches_select_own on patches;
create policy patches_select_own on patches
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists patches_insert_own on patches;
create policy patches_insert_own on patches
    for insert to authenticated
    with check (user_id = (select auth.uid()));

-- Accept / decline. The single-decision rule is enforced by the trigger in
-- 0005, not here: RLS sees rows, not state machines.
drop policy if exists patches_update_own on patches;
create policy patches_update_own on patches
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists patches_delete_own on patches;
create policy patches_delete_own on patches
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- resume_jobs
-- --------------------------------------------------------------------------
drop policy if exists resume_jobs_select_own on resume_jobs;
create policy resume_jobs_select_own on resume_jobs
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists resume_jobs_insert_own on resume_jobs;
create policy resume_jobs_insert_own on resume_jobs
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists resume_jobs_update_own on resume_jobs;
create policy resume_jobs_update_own on resume_jobs
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists resume_jobs_delete_own on resume_jobs;
create policy resume_jobs_delete_own on resume_jobs
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- chat_sessions
-- --------------------------------------------------------------------------
drop policy if exists chat_sessions_select_own on chat_sessions;
create policy chat_sessions_select_own on chat_sessions
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists chat_sessions_insert_own on chat_sessions;
create policy chat_sessions_insert_own on chat_sessions
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists chat_sessions_update_own on chat_sessions;
create policy chat_sessions_update_own on chat_sessions
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists chat_sessions_delete_own on chat_sessions;
create policy chat_sessions_delete_own on chat_sessions
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- chat_messages
-- --------------------------------------------------------------------------
-- Checked on the row's own user_id rather than by joining to chat_sessions.
-- A join in a policy runs per row and has to be RLS-checked itself; the
-- denormalised column makes this an index lookup. The join condition
-- (message belongs to a session the user owns) is a data-integrity concern,
-- handled by the FK plus the fact that only the owner can create the session.
drop policy if exists chat_messages_select_own on chat_messages;
create policy chat_messages_select_own on chat_messages
    for select to authenticated
    using (user_id = (select auth.uid()));

drop policy if exists chat_messages_insert_own on chat_messages;
create policy chat_messages_insert_own on chat_messages
    for insert to authenticated
    with check (user_id = (select auth.uid()));

drop policy if exists chat_messages_update_own on chat_messages;
create policy chat_messages_update_own on chat_messages
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists chat_messages_delete_own on chat_messages;
create policy chat_messages_delete_own on chat_messages
    for delete to authenticated
    using (user_id = (select auth.uid()));

-- --------------------------------------------------------------------------
-- step_traces
-- --------------------------------------------------------------------------
-- Read-only to the user: traces are written by the backend as service_role.
-- Giving the browser INSERT would let a client fabricate its own cost and
-- latency records, which are the numbers billing and alerting read.
drop policy if exists step_traces_select_own on step_traces;
create policy step_traces_select_own on step_traces
    for select to authenticated
    using (user_id = (select auth.uid()));

-- (no insert/update/delete policies for authenticated — intentional)

-- --------------------------------------------------------------------------
-- step_cache — RLS ENABLED, NO POLICIES
-- --------------------------------------------------------------------------
-- RLS with zero policies denies everything to every non-bypassing role. That
-- is the intent: this table is shared across tenants by design (see the long
-- comment in 0001) and therefore must never be reachable from a browser
-- holding a user's JWT.
--
-- Why "enable RLS with no policy" rather than "leave RLS off":
--   * A table in the `public` schema with RLS disabled is exposed by PostgREST
--     and readable by anyone the GRANTs allow. Supabase's own linter flags
--     exactly this. Relying on the absence of a GRANT is one `grant all on all
--     tables in schema public` away from a full cross-tenant dump of every
--     cached model output.
--   * Denying by default means a future GRANT — added by a tool, a template or
--     a well-meaning migration — still cannot read a single row.
-- Both belts are fastened: no grant to anon/authenticated, AND no policy.
-- Only service_role (BYPASSRLS) touches it.

-- --------------------------------------------------------------------------
-- storage_gc_queue — same treatment, same reasons
-- --------------------------------------------------------------------------
-- It holds storage paths belonging to users who may already be deleted, and it
-- is drained by a background worker. Nothing a browser does should ever read
-- or write it. RLS enabled, no policies, no grants outside service_role.


-- ============ 0003_indexes.sql ============

-- 0003_indexes.sql
--
-- Indexes, in their own migration so that adding one later is a one-line diff
-- with no chance of touching a table definition.
--
-- Two rules shaped this list:
--
-- 1. EVERY RLS PREDICATE NEEDS AN INDEX. `user_id = (select auth.uid())` is
--    applied to every single query against every user-scoped table. Without an
--    index on user_id, that predicate is a sequential scan of the whole
--    tenant-wide table on every request, and the scan gets slower as other
--    people sign up. Composite indexes leading with user_id serve both the
--    policy and the query.
--
-- 2. LEAD WITH THE EQUALITY COLUMN, END WITH THE SORT. `(user_id, updated_at
--    desc)` lets Postgres seek to the tenant and then walk the index in
--    already-sorted order, so "my resumes, newest first, limit 20" reads
--    twenty index entries and stops. The reverse order would force a sort of
--    everything the user owns.

-- --------------------------------------------------------------------------
-- documents
-- --------------------------------------------------------------------------
create index if not exists documents_user_created_idx
    on documents (user_id, created_at desc);

-- Content lookup: "have we already extracted this exact text?" — the surviving
-- half of store.py's fingerprint idea. Not unique on its own (the unique
-- constraint is per user, in 0001); this one serves dedupe analytics and the
-- service-role path that answers the question before a user_id is in hand.
create index if not exists documents_sha256_idx
    on documents (sha256)
    where sha256 is not null;

-- --------------------------------------------------------------------------
-- facts
-- --------------------------------------------------------------------------
-- The truth guard's hot path: given a tailored line citing 'E1.B2', fetch that
-- fact for this user. Equality on both columns, so plain btree order is fine.
create index if not exists facts_user_key_idx
    on facts (user_id, fact_key);

-- "Show me everything extracted from this upload", and the cascade path when a
-- document is deleted. An unindexed FK makes every parent delete a full scan
-- of the child table.
create index if not exists facts_document_idx
    on facts (document_id)
    where document_id is not null;

-- The guard only ever reads *currently believed* facts. A partial index on the
-- open rows keeps superseded history out of the hot index entirely, so the
-- index stops growing once a user's resume settles even as the ledger does not.
create index if not exists facts_user_current_idx
    on facts (user_id, fact_key)
    where valid_to is null;

-- --------------------------------------------------------------------------
-- jobs
-- --------------------------------------------------------------------------
create index if not exists jobs_user_created_idx
    on jobs (user_id, created_at desc);

create index if not exists jobs_sha256_idx
    on jobs (sha256)
    where sha256 is not null;

-- --------------------------------------------------------------------------
-- resumes
-- --------------------------------------------------------------------------
-- The dashboard query, verbatim.
create index if not exists resumes_user_updated_idx
    on resumes (user_id, updated_at desc);

-- Lineage: "which tailored copies came from this master?"
create index if not exists resumes_base_idx
    on resumes (base_resume_id)
    where base_resume_id is not null;

create index if not exists resumes_job_idx
    on resumes (job_id)
    where job_id is not null;

-- Supports the composite FK's referential check and the 0004 trigger's lookup.
create index if not exists resumes_current_version_idx
    on resumes (current_version_id)
    where current_version_id is not null;

-- --------------------------------------------------------------------------
-- resume_versions
-- --------------------------------------------------------------------------
-- The history pane, and the trigger that recomputes current_version_id: both
-- want "newest version of this resume" as a single index seek.
create index if not exists resume_versions_resume_created_idx
    on resume_versions (resume_id, created_at desc);

create index if not exists resume_versions_user_created_idx
    on resume_versions (user_id, created_at desc);

create index if not exists resume_versions_parent_idx
    on resume_versions (parent_id)
    where parent_id is not null;

-- --------------------------------------------------------------------------
-- patches
-- --------------------------------------------------------------------------
create index if not exists patches_resume_status_idx
    on patches (resume_id, status);

-- The partial index that pays. The editor asks "what is still pending on this
-- resume?" on every render, while accepted and declined patches accumulate
-- forever and are read only by the history view. Restricting to 'proposed'
-- keeps this index roughly constant-sized — usually a handful of rows per
-- resume — no matter how long the audit trail grows.
create index if not exists patches_resume_proposed_idx
    on patches (resume_id)
    where status = 'proposed';

create index if not exists patches_user_created_idx
    on patches (user_id, created_at desc);

create index if not exists patches_base_version_idx
    on patches (base_version_id);

-- --------------------------------------------------------------------------
-- resume_jobs
-- --------------------------------------------------------------------------
-- (resume_id, job_id) is already covered by the unique constraint in 0001.
-- This is the other direction: "every resume I have aimed at this job".
create index if not exists resume_jobs_job_idx
    on resume_jobs (job_id);

create index if not exists resume_jobs_user_created_idx
    on resume_jobs (user_id, created_at desc);

-- --------------------------------------------------------------------------
-- chat
-- --------------------------------------------------------------------------
create index if not exists chat_sessions_resume_created_idx
    on chat_sessions (resume_id, created_at desc);

create index if not exists chat_sessions_user_created_idx
    on chat_sessions (user_id, created_at desc);

-- Transcript replay, in insertion order. ASC, not DESC: a conversation is read
-- oldest-first, and the index direction should match how it is scanned.
create index if not exists chat_messages_session_created_idx
    on chat_messages (session_id, created_at);

create index if not exists chat_messages_user_created_idx
    on chat_messages (user_id, created_at desc);

-- --------------------------------------------------------------------------
-- step_traces
-- --------------------------------------------------------------------------
create index if not exists step_traces_user_created_idx
    on step_traces (user_id, created_at desc);

create index if not exists step_traces_resume_created_idx
    on step_traces (resume_id, created_at desc)
    where resume_id is not null;

-- Alerting reads only the failures, which are a tiny fraction of rows. A
-- partial index makes "recent errors" cheap without indexing the happy path.
create index if not exists step_traces_failures_idx
    on step_traces (created_at desc)
    where ok = false;

-- --------------------------------------------------------------------------
-- step_cache
-- --------------------------------------------------------------------------
-- cache_key is the primary key, which is the only lookup the read path makes.
-- This index serves eviction ("oldest, least-used entries first"), which is a
-- background job and would otherwise scan the whole cache.
create index if not exists step_cache_step_created_idx
    on step_cache (step, created_at);

-- --------------------------------------------------------------------------
-- storage_gc_queue
-- --------------------------------------------------------------------------
-- The worker's claim query: undeleted rows, oldest first. Partial, because
-- completed rows are kept for audit and are never polled.
create index if not exists storage_gc_queue_pending_idx
    on storage_gc_queue (enqueued_at)
    where deleted_at is null;


-- ============ 0004_tenant_integrity.sql ============

-- 0004_tenant_integrity.sql
--
-- Composite foreign keys that make a cross-tenant reference structurally
-- impossible, not merely unlikely.
--
-- THE HOLE THIS CLOSES
--   RLS checks the row you are writing. It does not check what that row points
--   at. Consider, with only the single-column FKs from 0001:
--
--       -- as user B, knowing (or guessing) user A's resume id
--       insert into resume_versions (user_id, resume_id, doc_json, created_by)
--       values (B, '<A''s resume>', '{"headline":"pwned"}', 'user');
--
--   Every check passes. The insert policy is satisfied (user_id = B). The FK
--   is satisfied (A's resume exists). B has written a row into A's document
--   history — and the trigger in 0005, which points a resume at its newest
--   version, would then make A's resume render B's content. B cannot read the
--   row back, so this is not a read leak; it is a write leak, which is worse.
--
--   The same shape exists for every child that references a parent: a patch
--   against someone else's version, a chat message in someone else's session,
--   a resume_jobs row joining your resume to their job, a fact attached to
--   their document.
--
-- THE FIX
--   Give every parent a `unique (id, user_id)` and make the child's FK
--   composite: `(parent_id, user_id) references parent (id, user_id)`. The
--   child's own user_id — already pinned to the caller by RLS — is now part of
--   the reference, so a row can only point at a parent belonging to the same
--   user. The database rejects the insert above with a foreign key violation
--   and no application code is involved.
--
--   `unique (id, user_id)` on a table whose id is already a primary key costs
--   one extra index and adds no new constraint on the data; it exists purely
--   to be a valid FK target.
--
--   The single-column FKs from 0001 are kept alongside. They are redundant for
--   integrity but they document intent, and dropping one later (say, to change
--   a delete rule) should not silently take the tenant check with it.

-- --------------------------------------------------------------------------
-- Parents: advertise (id, user_id) as a referenceable key
-- --------------------------------------------------------------------------
do $$
declare
    t text;
begin
    foreach t in array array[
        -- facts is in this list because it is its own parent (supersedes).
        'documents', 'jobs', 'resumes', 'resume_versions', 'chat_sessions', 'facts'
    ]
    loop
        if not exists (
            select 1 from pg_constraint
            where conname = t || '_id_user_key'
              and conrelid = format('public.%I', t)::regclass
        ) then
            execute format(
                'alter table public.%I add constraint %I unique (id, user_id)',
                t, t || '_id_user_key');
        end if;
    end loop;
end $$;

-- --------------------------------------------------------------------------
-- Children: composite FKs
-- --------------------------------------------------------------------------

-- facts -> documents. `set null` on both columns is not possible here because
-- user_id is NOT NULL, so the tenant half of the key must survive the delete.
-- `on delete set null (document_id)` (PG 15+) nulls only the document pointer,
-- which is exactly the behaviour 0001 argued for: the fact outlives the file.
alter table facts drop constraint if exists facts_document_tenant_fkey;
alter table facts add constraint facts_document_tenant_fkey
    foreign key (document_id, user_id) references documents (id, user_id)
    on delete set null (document_id);

-- facts -> facts (supersedes). A fact may only supersede another fact of the
-- same user; otherwise B could retire A's claim out from under the guard.
alter table facts drop constraint if exists facts_supersedes_tenant_fkey;
alter table facts add constraint facts_supersedes_tenant_fkey
    foreign key (supersedes, user_id) references facts (id, user_id)
    on delete set null (supersedes);

-- resumes -> resumes (base_resume_id) and -> jobs (job_id)
alter table resumes drop constraint if exists resumes_base_tenant_fkey;
alter table resumes add constraint resumes_base_tenant_fkey
    foreign key (base_resume_id, user_id) references resumes (id, user_id)
    on delete set null (base_resume_id);

alter table resumes drop constraint if exists resumes_job_tenant_fkey;
alter table resumes add constraint resumes_job_tenant_fkey
    foreign key (job_id, user_id) references jobs (id, user_id)
    on delete set null (job_id);

-- resume_versions -> resumes, and -> resume_versions (parent_id)
alter table resume_versions drop constraint if exists resume_versions_resume_tenant_fkey;
alter table resume_versions add constraint resume_versions_resume_tenant_fkey
    foreign key (resume_id, user_id) references resumes (id, user_id)
    on delete cascade;

alter table resume_versions drop constraint if exists resume_versions_parent_tenant_fkey;
alter table resume_versions add constraint resume_versions_parent_tenant_fkey
    foreign key (parent_id, user_id) references resume_versions (id, user_id)
    on delete set null (parent_id);

-- patches -> resumes, -> resume_versions (base and applied)
alter table patches drop constraint if exists patches_resume_tenant_fkey;
alter table patches add constraint patches_resume_tenant_fkey
    foreign key (resume_id, user_id) references resumes (id, user_id)
    on delete cascade;

alter table patches drop constraint if exists patches_base_version_tenant_fkey;
alter table patches add constraint patches_base_version_tenant_fkey
    foreign key (base_version_id, user_id) references resume_versions (id, user_id)
    on delete cascade;

alter table patches drop constraint if exists patches_applied_version_tenant_fkey;
alter table patches add constraint patches_applied_version_tenant_fkey
    foreign key (applied_version_id, user_id) references resume_versions (id, user_id)
    on delete set null (applied_version_id);

-- resume_jobs -> resumes, -> jobs
alter table resume_jobs drop constraint if exists resume_jobs_resume_tenant_fkey;
alter table resume_jobs add constraint resume_jobs_resume_tenant_fkey
    foreign key (resume_id, user_id) references resumes (id, user_id)
    on delete cascade;

alter table resume_jobs drop constraint if exists resume_jobs_job_tenant_fkey;
alter table resume_jobs add constraint resume_jobs_job_tenant_fkey
    foreign key (job_id, user_id) references jobs (id, user_id)
    on delete cascade;

-- chat_sessions -> resumes
alter table chat_sessions drop constraint if exists chat_sessions_resume_tenant_fkey;
alter table chat_sessions add constraint chat_sessions_resume_tenant_fkey
    foreign key (resume_id, user_id) references resumes (id, user_id)
    on delete cascade;

-- chat_messages -> chat_sessions. This is what makes the denormalised user_id
-- on chat_messages safe: 0002 checks the local column instead of joining to
-- the session, and this constraint guarantees the two can never disagree.
alter table chat_messages drop constraint if exists chat_messages_session_tenant_fkey;
alter table chat_messages add constraint chat_messages_session_tenant_fkey
    foreign key (session_id, user_id) references chat_sessions (id, user_id)
    on delete cascade;

-- step_traces -> resumes
alter table step_traces drop constraint if exists step_traces_resume_tenant_fkey;
alter table step_traces add constraint step_traces_resume_tenant_fkey
    foreign key (resume_id, user_id) references resumes (id, user_id)
    on delete set null (resume_id);


-- ============ 0005_triggers.sql ============

-- 0005_triggers.sql
--
-- Invariants that a constraint cannot express, because they are about the
-- transition rather than the row.
--
-- Everything here is enforced in the database rather than in the API on
-- purpose. There will be more than one writer — the Next.js app through
-- PostgREST, the Python backend as service_role, a future background worker,
-- and psql at 2am during an incident. An invariant that lives in one of those
-- is not an invariant.
--
-- SECURITY DEFINER is used only where a trigger must write to a table the
-- calling user has no grant on (storage_gc_queue). Each such function pins
-- `search_path`, without which a caller could create a shadowing object in a
-- schema earlier on the path and have it executed with the definer's rights.

-- --------------------------------------------------------------------------
-- updated_at maintenance
-- --------------------------------------------------------------------------
-- Written as a generic function keyed off the NEW record so any table that
-- grows an updated_at column can reuse it. Not written with a hardcoded table
-- name, and not left to the client: a client-supplied updated_at is a clock
-- the server does not control, and "sort by most recently edited" then depends
-- on the user's laptop being right about the time.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists resumes_set_updated_at on resumes;
create trigger resumes_set_updated_at
    before update on resumes
    for each row
    execute function public.set_updated_at();

-- --------------------------------------------------------------------------
-- resumes.current_version_id follows the newest version
-- --------------------------------------------------------------------------
-- The pointer is a cache of `select id from resume_versions where resume_id =
-- ? order by created_at desc limit 1`. Caches drift, so it is maintained here
-- rather than by whoever happened to write the version.
--
-- Ordering is (created_at desc, id desc). created_at alone is not a total
-- order: two versions inserted in the same statement share now(), and a tie
-- would make "newest" nondeterministic and the pointer flap between reads.
-- id is the deterministic tiebreak.
--
-- DECISION — an INSERT always wins.
--   A new version is the newest by definition, and comparing timestamps to
--   decide would mean a clock skew or a backdated import could leave the
--   pointer on an older row. Imports that must not move the head should insert
--   and then explicitly re-point.
--
-- DECISION — DELETE recomputes rather than nulls.
--   Deleting the current version must leave the pointer on the next-newest
--   surviving version, not on null; a resume with versions but no current
--   version renders as empty. The composite FK's `on delete set null
--   (current_version_id)` fires first and nulls the column; this trigger then
--   fills it back in. Order matters and is guaranteed: referential actions run
--   before AFTER-row triggers on the referencing table complete.
--
-- DECISION — the resume-delete case is a no-op, not an error.
--   Deleting a resume cascades to its versions, and this trigger would then
--   try to update a resume row that is mid-delete. The existence check short-
--   circuits that; without it, deleting a resume raises.
create or replace function public.sync_current_version()
returns trigger
language plpgsql
as $$
declare
    target_resume uuid := coalesce(new.resume_id, old.resume_id);
    newest        uuid;
begin
    if tg_op = 'INSERT' then
        update resumes
           set current_version_id = new.id
         where id = target_resume;
        return new;
    end if;

    -- DELETE. If the parent resume is itself being deleted there is nothing
    -- to point anywhere.
    if not exists (select 1 from resumes where id = target_resume) then
        return old;
    end if;

    select v.id
      into newest
      from resume_versions v
     where v.resume_id = target_resume
     order by v.created_at desc, v.id desc
     limit 1;

    update resumes
       set current_version_id = newest
     where id = target_resume
       and current_version_id is distinct from newest;

    return old;
end;
$$;

drop trigger if exists resume_versions_sync_current on resume_versions;
create trigger resume_versions_sync_current
    after insert or delete on resume_versions
    for each row
    execute function public.sync_current_version();

-- --------------------------------------------------------------------------
-- facts: append-only, enforced per column
-- --------------------------------------------------------------------------
-- 0002 withholds the DELETE policy and allows UPDATE only so that a row can be
-- retired. This trigger is the other half: it says *which column* an update
-- may touch. Both are needed, and for different attackers — the policy stops
-- another tenant, the trigger stops our own backend (running as service_role,
-- which bypasses RLS entirely) from quietly rewriting history.
--
-- valid_to is the only mutable column, and it may only be set, never cleared
-- or moved: un-retiring a fact would resurrect a claim the user withdrew.
--
-- ONE EXEMPTION. The ON DELETE SET NULL actions from 0001/0004 (document_id
-- when an upload is deleted, supersedes when a superseding fact is removed)
-- are updates performed by the constraint, and they still fire row triggers.
-- The guard recognises them by shape: the only change is a protected pointer
-- going to NULL and nothing else moves. No ordinary statement doing anything
-- meaningful has that shape, so allowing it does not open a hole.
create or replace function public.facts_append_only_guard()
returns trigger
language plpgsql
as $$
declare
    only_pointer_nulled boolean;
begin
    if tg_op = 'DELETE' then
        raise exception
            'facts is append-only: supersede % instead of deleting it', old.id
            using errcode = 'restrict_violation';
    end if;

    -- ON DELETE SET NULL from documents/facts: document_id or supersedes goes
    -- to null and nothing else moves.
    only_pointer_nulled :=
        (new.id, new.user_id, new.fact_key, new.text, new.origin,
         new.entities_json, new.evidence_json, new.valid_from,
         new.valid_to, new.created_at)
        is not distinct from
        (old.id, old.user_id, old.fact_key, old.text, old.origin,
         old.entities_json, old.evidence_json, old.valid_from,
         old.valid_to, old.created_at)
        and (
            (new.document_id is null and old.document_id is not null)
            or (new.supersedes is null and old.supersedes is not null)
        )
        and (new.document_id is null or new.document_id = old.document_id)
        and (new.supersedes is null or new.supersedes = old.supersedes);

    if only_pointer_nulled then
        return new;
    end if;

    if (new.id, new.user_id, new.document_id, new.fact_key, new.text, new.origin,
        new.entities_json, new.evidence_json, new.supersedes, new.valid_from,
        new.created_at)
       is distinct from
       (old.id, old.user_id, old.document_id, old.fact_key, old.text, old.origin,
        old.entities_json, old.evidence_json, old.supersedes, old.valid_from,
        old.created_at)
    then
        raise exception
            'facts is append-only: only valid_to may be updated (fact %)', old.id
            using errcode = 'restrict_violation';
    end if;

    if old.valid_to is not null and new.valid_to is distinct from old.valid_to then
        raise exception
            'fact % was already retired at %; it cannot be re-opened or re-dated',
            old.id, old.valid_to
            using errcode = 'restrict_violation';
    end if;

    return new;
end;
$$;

drop trigger if exists facts_append_only on facts;
create trigger facts_append_only
    before update or delete on facts
    for each row
    execute function public.facts_append_only_guard();

-- --------------------------------------------------------------------------
-- facts: inserting a superseding row retires the one it replaces
-- --------------------------------------------------------------------------
-- Doing this in the database means the two writes cannot come apart. If the
-- application did it, a crash between the insert and the update would leave
-- two rows both claiming to be the current E1.B2, and the guard would pick
-- whichever the planner returned first.
create or replace function public.facts_retire_superseded()
returns trigger
language plpgsql
as $$
begin
    if new.supersedes is not null then
        update facts
           set valid_to = new.valid_from
         where id = new.supersedes
           and valid_to is null;
    end if;
    return new;
end;
$$;

drop trigger if exists facts_retire_superseded on facts;
create trigger facts_retire_superseded
    after insert on facts
    for each row
    execute function public.facts_retire_superseded();

-- --------------------------------------------------------------------------
-- patches: a decision is final
-- --------------------------------------------------------------------------
-- DECISION — can a patch be accepted twice? No.
--   Two things make double-application possible without this: a double-clicked
--   Accept button, and a retry after a timeout where the first request
--   actually succeeded. Both replay the same UPDATE. Applying the same ops
--   twice duplicates bullets or, worse, applies an insert op at a path that
--   has shifted.
--
--   The guard is a state machine, not a uniqueness constraint, because the
--   thing to forbid is a transition. 'proposed' is the only state an update
--   may leave; once a patch is accepted, declined or superseded the row is
--   FROZEN and any further UPDATE raises. Frozen rather than "may not change
--   status", because a replayed request usually sends the identical value:
--   `set status = 'accepted'` on an already-accepted patch changes no column,
--   so a transition check would wave it through and the caller would go on to
--   apply the ops a second time.
--
--   THE ACCEPT FLOW THIS IMPLIES, in one transaction:
--     1. insert the resulting resume_version
--     2. update the patch ONCE, setting status='accepted' and
--        applied_version_id together
--   Not the other order. A second update to fill in applied_version_id would
--   hit the freeze, which is the point: there is exactly one write that
--   decides a patch, and a retry of it fails loudly.
create or replace function public.patches_decision_guard()
returns trigger
language plpgsql
as $$
begin
    if old.status <> 'proposed' then
        raise exception
            'patch % was already % at %; a decided patch is immutable',
            old.id, old.status, old.decided_at
            using errcode = 'invalid_parameter_value',
                  hint = 'Create a new patch instead of re-deciding this one.';
    end if;

    -- Stamp the decision time server-side so the CHECK in 0001 is satisfied
    -- without every caller remembering to set it.
    if new.status <> 'proposed' and new.decided_at is null then
        new.decided_at := now();
    end if;

    return new;
end;
$$;

drop trigger if exists patches_decision on patches;
create trigger patches_decision
    before update on patches
    for each row
    execute function public.patches_decision_guard();

-- --------------------------------------------------------------------------
-- documents: enqueue the storage object for deletion
-- --------------------------------------------------------------------------
-- The orphaned-object problem stated in 0001. `on delete cascade` from
-- auth.users removes the document row and nothing in storage; the bytes stay
-- on S3 forever, which is a cost problem and an erasure-request failure.
--
-- SECURITY DEFINER because the queue has no grant to `authenticated` — the
-- user must not be able to read or forge queue entries, but their delete must
-- still be able to create one. search_path is pinned for the usual reason.
create or replace function public.enqueue_storage_gc()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if old.storage_path is not null and old.storage_path <> '' then
        insert into public.storage_gc_queue (bucket_id, storage_path, owner_id)
        values ('resumes', old.storage_path, old.user_id);
    end if;
    return old;
end;
$$;

revoke all on function public.enqueue_storage_gc() from public;

drop trigger if exists documents_enqueue_storage_gc on documents;
create trigger documents_enqueue_storage_gc
    after delete on documents
    for each row
    execute function public.enqueue_storage_gc();

-- --------------------------------------------------------------------------
-- step_cache: count hits without a round trip
-- --------------------------------------------------------------------------
-- Not a trigger — a trigger cannot observe a SELECT. This is the read path the
-- backend should call instead of a bare select, so `hits` is a real number
-- rather than one nobody remembered to increment. Returns null on a miss.
--
-- Note what it does NOT do: derive the key. Key derivation is where the
-- cross-tenant rule in 0001 lives, and it stays in application code where it
-- can be unit-tested against a list of known-PII step names.
create or replace function public.step_cache_get(p_cache_key text)
returns jsonb
language sql
security definer
set search_path = public, pg_temp
as $$
    update public.step_cache
       set hits = hits + 1
     where cache_key = p_cache_key
    returning output_json;
$$;

revoke all on function public.step_cache_get(text) from public;
grant execute on function public.step_cache_get(text) to service_role;


-- ============ 0006_storage.sql ============

-- 0006_storage.sql
--
-- The private `resumes` bucket and its access rules.
--
-- THE PATH CONVENTION IS THE SECURITY MODEL
--   Every object is stored as `<uid>/<document_id>.<ext>` — the owner's uid is
--   the first path segment, and the policies below compare that segment to
--   `(select auth.uid())`. There is no separate ownership table to keep in
--   sync, and no way to write an object outside your own folder: the INSERT
--   policy checks the path you are writing to, not the row you claim to own.
--
--   `storage.objects.owner` is deliberately NOT used as the check. It records
--   whoever uploaded the object, which is the right value in normal flows but
--   is null for service-role uploads and does not constrain the *path*. Two
--   users could then both write `shared/cv.pdf` and overwrite each other.
--   Keying on the path makes collisions impossible by construction.
--
-- PRIVATE, NOT PUBLIC
--   `public = false`. A public bucket serves every object to anyone who knows
--   or guesses the URL, with no policy evaluation at all. Resumes contain a
--   full name, an email, a phone number and an employment history; a leaked
--   URL is a leaked identity document. Clients get time-limited signed URLs
--   instead.

-- --------------------------------------------------------------------------
-- The bucket
-- --------------------------------------------------------------------------
-- Idempotent: `supabase db reset` re-runs every migration against a database
-- where storage.buckets may already hold the row.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'resumes',
    'resumes',
    false,
    10485760,  -- 10 MB. A resume that does not fit in 10 MB is a scanned image
               -- of a resume, which the text extractor cannot read anyway, so
               -- rejecting it at upload gives a better error than failing later.
    array[
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/msword',
        'text/plain'
    ]
)
on conflict (id) do update
    set public             = excluded.public,
        file_size_limit    = excluded.file_size_limit,
        allowed_mime_types = excluded.allowed_mime_types;

-- --------------------------------------------------------------------------
-- Object policies
-- --------------------------------------------------------------------------
-- storage.objects already has RLS enabled by Supabase; we only add policies.
-- As in 0002: one policy per operation, `(select auth.uid())` rather than the
-- bare call, and every policy scoped to `bucket_id = 'resumes'` so it cannot
-- accidentally govern some future bucket.
--
-- `storage.foldername(name)` splits the object path and returns the directory
-- segments as a text[]; element 1 is the top-level folder, which by convention
-- above is the owner's uid.

drop policy if exists "resumes read own" on storage.objects;
create policy "resumes read own" on storage.objects
    for select to authenticated
    using (
        bucket_id = 'resumes'
        and (storage.foldername(name))[1] = (select auth.uid())::text
    );

drop policy if exists "resumes upload own" on storage.objects;
create policy "resumes upload own" on storage.objects
    for insert to authenticated
    with check (
        bucket_id = 'resumes'
        and (storage.foldername(name))[1] = (select auth.uid())::text
    );

-- Both clauses matter. `using` stops you targeting somebody else's object;
-- `with check` stops you *moving* your own object into their folder, which a
-- rename is: storage implements move as an UPDATE of `name`.
drop policy if exists "resumes update own" on storage.objects;
create policy "resumes update own" on storage.objects
    for update to authenticated
    using (
        bucket_id = 'resumes'
        and (storage.foldername(name))[1] = (select auth.uid())::text
    )
    with check (
        bucket_id = 'resumes'
        and (storage.foldername(name))[1] = (select auth.uid())::text
    );

drop policy if exists "resumes delete own" on storage.objects;
create policy "resumes delete own" on storage.objects
    for delete to authenticated
    using (
        bucket_id = 'resumes'
        and (storage.foldername(name))[1] = (select auth.uid())::text
    );

-- --------------------------------------------------------------------------
-- What still is not automatic
-- --------------------------------------------------------------------------
-- Deleting a `documents` row does NOT delete its object: they are different
-- subsystems and Postgres cannot reach S3. `enqueue_storage_gc` (0005) pushes
-- the path onto storage_gc_queue and a service-role worker drains it with:
--
--     select id, bucket_id, storage_path
--       from storage_gc_queue
--      where deleted_at is null
--      order by enqueued_at
--      limit 100
--        for update skip locked;
--     -- supabase.storage.from(bucket).remove([storage_path])
--     update storage_gc_queue set deleted_at = now() where id = any($1);
--
-- The same worker handles account deletion, because the cascade from
-- auth.users empties `documents` and therefore fires the same trigger for
-- every one of that user's uploads. The queue is the only place that record
-- survives the user, which is why it holds a plain uuid rather than an FK.


-- ============ 0007_resume_source_document.sql ============

-- ---------------------------------------------------------------------------
-- 0007 — a resume remembers the upload it came from
-- ---------------------------------------------------------------------------
--
-- THE GAP THIS CLOSES
--
-- The onboarding flow is: upload a file, which inserts a `documents` row and
-- carries its id forward as `?document=<uuid>`; then choose a template, which
-- inserts a `resumes` row. Nothing joined those two. The query parameter was
-- read to build the next URL and then dropped, and `resumes` had nowhere to
-- put it, so the connection existed only in the address bar and died with the
-- first reload.
--
-- That is not a cosmetic loss. The truth guard checks every rewritten line
-- against the text of the resume the candidate actually uploaded, and
-- `documents.raw_text` is where that text lives. A resume that cannot name its
-- source document cannot be verified against anything, which means the one
-- feature this product exists for silently stops working. It would have
-- presented as "the guard passes everything", which is the worst possible
-- shape for that bug: it looks like success.
--
-- WHY NOT GO THROUGH facts
--
-- `facts.document_id` exists, so the link could be inferred by joining facts
-- to the resume. It cannot: facts are extracted per document and are shared
-- across every resume tailored from that document, so the join is one-to-many
-- in the wrong direction, and a resume with no facts extracted yet — which is
-- every resume at the moment it is created — would have no answer at all.
--
-- ON DELETE SET NULL, NOT CASCADE
--
-- Deleting an upload is retracting a file, not retracting the resumes already
-- written from it and sent to employers. This matches how 0004 treats
-- `facts.document_id` for the same reason. The consequence is that the guard
-- loses its corpus for that resume, which the application must surface rather
-- than treat as "nothing to check".

alter table resumes
    add column if not exists source_document_id uuid;

comment on column resumes.source_document_id is
    'The upload this resume was created from. Null for a resume started from '
    'scratch, or one whose source document was deleted. The truth guard reads '
    'documents.raw_text through this, so a null here means the guard has no '
    'corpus and the application must say so rather than report a pass.';

-- Composite, for the same reason every other child key in 0004 is composite:
-- row-level security checks the row being written, not the row it points at.
-- With a single-column reference, one tenant could attach another tenant's
-- document to their own resume and every policy would still pass.
alter table resumes
    drop constraint if exists resumes_source_document_fkey;

alter table resumes
    add constraint resumes_source_document_fkey
    foreign key (source_document_id, user_id)
    references documents (id, user_id)
    on delete set null (source_document_id);

-- The editor's first query is "which document backs this resume", and the
-- reverse, "which resumes came from this upload", is what makes deleting one
-- answerable. Partial, because a scratch resume has nothing to look up.
create index if not exists resumes_source_document
    on resumes (source_document_id)
    where source_document_id is not null;


-- ============ 0008_documents_facts.sql ============

-- ---------------------------------------------------------------------------
-- 0008 — keep the extraction beside the document it came from
-- ---------------------------------------------------------------------------
--
-- WHY THIS IS NOT REDUNDANT WITH THE facts TABLE
--
-- It stores the same information twice and that is deliberate, because the
-- two copies answer different questions and have different lifetimes.
--
--   facts (the table)   is the ledger. One row per citable claim, each with
--                       an origin, evidence, and the ability to be
--                       superseded when the candidate corrects themselves.
--                       It is append-only and it grows: a fact the user
--                       attests in conversation lands here and never came
--                       from any document. It answers "may this line cite
--                       that?" and "who said so, and when".
--
--   documents.facts_json is the extractor's output, unchanged. One nested
--                       object, exactly as the model returned it. It answers
--                       "what shape was this resume in", which the ledger
--                       cannot: flattening a role into a row loses the
--                       nesting that says which bullets belong to which
--                       employer, and no amount of parsing `fact_key` back
--                       out reconstructs it faithfully.
--
-- The concrete need: opening the editor on a freshly uploaded resume has to
-- render the candidate's own document, in their chosen template, before
-- anything has been tailored. That means rebuilding a full document from the
-- extraction, and rebuilding it from flattened rows would silently reorder
-- and re-parent bullets. A user who uploads a resume and is shown something
-- subtly rearranged has been lied to on the first screen.
--
-- It also makes a second resume from the same upload free. Extraction is the
-- expensive step and its input has not changed.
--
-- NOT A CACHE THAT MAY BE WRONG. If the extraction contract changes, this is
-- stale in the same way the ledger is stale, and both are rebuilt from
-- raw_text together. It is not load-bearing for verification: the truth
-- guard reads raw_text and the ledger, never this.

alter table documents
    add column if not exists facts_json jsonb;

comment on column documents.facts_json is
    'The structured extraction, exactly as the model returned it. Used to '
    'rebuild the candidate''s own document for the editor before anything is '
    'tailored, which the flattened facts table cannot do without losing which '
    'bullets belong to which role. Null until parsed, and null forever if '
    'parsing failed.';


-- ============ 0009_single_user.sql ============

-- ---------------------------------------------------------------------------
-- 0009 — single user. Authentication removed.
-- ---------------------------------------------------------------------------
--
-- READ THIS BEFORE DEPLOYING ANYTHING THAT RUNS THIS MIGRATION.
--
-- This turns a multi-tenant database into a single-user one. After it runs
-- there is no authentication and no row-level security, which means:
--
--   * Anyone who can reach the PostgREST endpoint with the publishable key
--     can read, change and delete every row in every table. The publishable
--     key is shipped to browsers by design, so in practice that is anyone
--     who can reach the site.
--   * Resumes are dense personal data: names, phone numbers, addresses,
--     employment history. There is no longer anything between that data and
--     the public internet except the obscurity of the project URL.
--
-- That is a deliberate choice for a local, single-operator install. It is
-- not a configuration to deploy. 0002_rls.sql is left in place and
-- unmodified so restoring tenancy is a matter of re-running it and
-- re-enabling the gate in the application, not of rewriting it.
--
-- WHY THE FOREIGN KEYS GO
--
-- Every table carried `user_id uuid not null references auth.users (id)`.
-- With no sign-in there is no auth.users row to point at, so the reference
-- would reject every insert. The column stays, defaulted to one fixed owner,
-- because dropping it would mean rewriting every composite key added in 0004
-- and every index in 0003, and because it is the hook tenancy hangs back on.
--
-- WHAT IS DELIBERATELY KEPT
--
--   * user_id on every row, defaulted rather than removed
--   * the composite foreign keys from 0004, which still stop a child row
--     pointing at a parent owned by a different id
--   * every trigger from 0005, including the append-only facts rule
--
-- The isolation tests in supabase/tests/rls_test.sql will fail after this,
-- and that is correct: they assert a property this migration removes.

-- --------------------------------------------------------------------------
-- The one owner
-- --------------------------------------------------------------------------
-- A fixed uuid rather than a random one, so the application and the database
-- agree without a lookup, and so a dump from one install loads into another.

create schema if not exists app;

create or replace function app.owner_id() returns uuid
    language sql immutable parallel safe
as $$ select '00000000-0000-0000-0000-00000000da7a'::uuid $$;

comment on function app.owner_id is
    'The single owner every row belongs to now that authentication is gone. '
    'Referenced by column defaults so the application never has to send it.';

-- --------------------------------------------------------------------------
-- The composite tenant keys have to go, and this is why
-- --------------------------------------------------------------------------
--
-- 0004 replaced every child foreign key with a composite one of the shape
-- `(child_ref, user_id) references parent (id, user_id)`. That was the right
-- design: row-level security checks the row being written and not the row it
-- points at, so a single-column key let one tenant attach their version to
-- another tenant's resume with every policy passing.
--
-- With one user they defend nothing, and they actively break two things:
--
--   1. Backfilling user_id is impossible while they exist. Updating a parent
--      orphans the child pair; updating the child first points it at a pair
--      that does not exist yet. There is no order that works, which is the
--      error this migration hit on its first run:
--        update or delete on table "documents" violates foreign key
--        constraint "resumes_source_document_fkey"
--
--   2. Even without a backfill they would break the next upload. A new row
--      takes the owner default while every existing row keeps its old uuid,
--      so a new resume pointing at an old document fails the composite check
--      on a pair that will never match.
--
-- So they are replaced by plain single-column keys carrying the same delete
-- behaviour. "This parent exists" is still enforced. "This parent belongs to
-- the same tenant" is not, because there is only one.
--
-- Restoring tenancy means re-running 0004 after re-running 0002.

do $$
declare
    r record;
begin
    for r in
        select conname, conrelid::regclass::text as tbl
        from pg_constraint
        where contype = 'f'
          and connamespace = 'public'::regnamespace
          and conname in (
            'chat_messages_session_tenant_fkey', 'chat_sessions_resume_tenant_fkey',
            'facts_document_tenant_fkey', 'facts_supersedes_tenant_fkey',
            'patches_applied_version_tenant_fkey', 'patches_base_version_tenant_fkey',
            'patches_resume_tenant_fkey', 'resume_jobs_job_tenant_fkey',
            'resume_jobs_resume_tenant_fkey', 'resume_versions_parent_tenant_fkey',
            'resume_versions_resume_tenant_fkey', 'resumes_base_tenant_fkey',
            'resumes_current_version_fkey', 'resumes_job_tenant_fkey',
            'resumes_source_document_fkey', 'step_traces_resume_tenant_fkey'
          )
    loop
        execute format('alter table %s drop constraint %I', r.tbl, r.conname);
    end loop;
end $$;

-- Single-column replacements. Same targets, same ON DELETE behaviour as the
-- composite versions they replace; only the tenant half is dropped.
alter table resumes
    add constraint resumes_source_document_fkey
    foreign key (source_document_id) references documents (id) on delete set null;

alter table resumes
    add constraint resumes_current_version_fkey
    foreign key (current_version_id) references resume_versions (id)
    on delete set null deferrable initially deferred;

-- --------------------------------------------------------------------------
-- Detach from auth.users, default the owner, open the tables
-- --------------------------------------------------------------------------

do $$
declare
    t text;
    c text;
    pol record;
begin
    foreach t in array array[
        'documents', 'facts', 'jobs', 'resumes', 'resume_versions',
        'patches', 'resume_jobs', 'chat_sessions', 'chat_messages',
        'step_traces', 'storage_gc_queue'
    ]
    loop
        if to_regclass('public.' || t) is null then
            continue;
        end if;

        -- 1. Drop every policy. Leaving them while RLS is off is worse than
        --    removing them: the next person to enable RLS gets rules that
        --    reference an auth.uid() that is always null, and every query
        --    silently returns nothing.
        for pol in
            select policyname from pg_policies
            where schemaname = 'public' and tablename = t
        loop
            execute format('drop policy if exists %I on public.%I', pol.policyname, t);
        end loop;

        execute format('alter table public.%I disable row level security', t);
        execute format('alter table public.%I no force row level security', t);

        -- 2. Drop only the references to auth.users. The composite keys
        --    between our own tables, added in 0004, are left alone: they
        --    still prevent a version being attached to somebody else's
        --    resume, which remains a real integrity rule even with one user.
        for c in
            select con.conname
            from pg_constraint con
            join pg_class rel on rel.oid = con.confrelid
            join pg_namespace ns on ns.oid = rel.relnamespace
            where con.conrelid = ('public.' || t)::regclass
              and con.contype = 'f'
              and ns.nspname = 'auth'
              and rel.relname = 'users'
        loop
            execute format('alter table public.%I drop constraint %I', t, c);
        end loop;

        -- 3. Default the owner, so no caller has to know the uuid.
        if exists (
            select 1 from information_schema.columns
            where table_schema = 'public' and table_name = t and column_name = 'user_id'
        ) then
            execute format(
                'alter table public.%I alter column user_id set default app.owner_id()', t
            );
            execute format('update public.%I set user_id = app.owner_id()', t);
        end if;

        -- 4. Grant the browser-facing role. With RLS off this is what makes
        --    the table reachable at all, and it is also precisely what makes
        --    the data public. See the warning at the top of this file.
        execute format('grant select, insert, update, delete on public.%I to anon', t);
    end loop;
end $$;

-- step_cache was service-role only and never user-scoped. It needs the same
-- grant now that there is no service role in the request path.
do $$
begin
    if to_regclass('public.step_cache') is not null then
        execute 'alter table public.step_cache disable row level security';
        execute 'grant select, insert, update, delete on public.step_cache to anon';
    end if;
end $$;

grant usage on schema public to anon;
grant usage on schema app to anon;
grant execute on function app.owner_id() to anon;
grant usage, select on all sequences in schema public to anon;

-- --------------------------------------------------------------------------
-- Storage
-- --------------------------------------------------------------------------
-- The bucket policies in 0006 keyed on (storage.foldername(name))[1] being
-- the caller's uid. With no caller there is no uid, so they are replaced by
-- one rule: the bucket is readable and writable.

do $$
declare
    pol record;
begin
    if to_regclass('storage.objects') is null then
        return;
    end if;

    for pol in
        select policyname from pg_policies
        where schemaname = 'storage' and tablename = 'objects'
          and policyname like 'resumes_%'
    loop
        execute format('drop policy if exists %I on storage.objects', pol.policyname);
    end loop;

    execute $p$
        create policy resumes_single_user on storage.objects
            for all to anon
            using (bucket_id = 'resumes')
            with check (bucket_id = 'resumes')
    $p$;
end $$;
