"""Freeze the scorer's behaviour as JSON, so the TypeScript port can be proved
identical rather than merely similar.

The scorer has to run twice in two languages. It runs in the browser on every
keystroke, because a score that arrives 150ms after you stop typing is a score
nobody watches; and it runs on the server, because the number a candidate is
shown has to be one the server agrees with.

Two implementations of one formula is a liability unless something holds them
together. This is that something: the Python scorer is the reference, these are
its answers, and the Vitest suite in packages/core consumes this exact file and
asserts the same numbers to one decimal place. A drift in either language fails
a test rather than quietly showing two different scores in two places.

    python scripts/export_score_fixtures.py            # writes the JSON
    python scripts/export_score_fixtures.py --check    # fails if it is stale

The --check mode is the one that belongs in CI. Editing the scorer without
re-exporting means the TypeScript port is now pinned to yesterday's answers,
which is exactly the failure this file exists to prevent.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(_ROOT / "src"), str(_ROOT)]

from atsresume.models import JobSpec, ResumeFacts, TailoredResume  # noqa: E402
from atsresume.pipeline import scoring as v1  # noqa: E402
from atsresume.pipeline import scoring_v2 as v2  # noqa: E402

OUT = _ROOT.parent / "packages" / "core" / "test" / "fixtures" / "scoring.json"


def _load_cases() -> list[tuple[str, TailoredResume]]:
    """The documents the v2 test suite already reasons about.

    Importing them rather than restating them means the fixtures cannot drift
    from the tests that justify them.
    """
    sys.path.insert(0, str(_ROOT / "tests"))
    from test_scoring_v2 import HONEST, LADDER, STUFFED  # type: ignore[import-not-found]

    cases = list(LADDER)
    cases.append(("honest", HONEST))
    cases.append(("stuffed", STUFFED))
    return cases


def _fixture_job() -> JobSpec:
    sys.path.insert(0, str(_ROOT / "tests"))
    from test_scoring_v2 import build_job  # type: ignore[import-not-found]

    return build_job()


def _fixture_facts() -> ResumeFacts:
    sys.path.insert(0, str(_ROOT / "scripts"))
    from sample import facts  # type: ignore[import-not-found]

    return facts()


def build() -> dict[str, Any]:
    job = _fixture_job()
    facts = _fixture_facts()

    cases: list[dict[str, Any]] = []
    for name, doc in _load_cases():
        breakdown = v2.compute_breakdown(job, facts, doc)
        report_v2 = v2.compute_ats_report(job, facts, doc)
        report_v1 = v1.compute_ats_report(job, facts, doc)
        cases.append(
            {
                "name": name,
                "tailored": doc.model_dump(mode="json"),
                "expected": {
                    "overall": report_v2.overall,
                    "sub_scores": report_v2.sub_scores.model_dump(mode="json"),
                    "matched_keywords": sorted(report_v2.matched_keywords),
                    "missing_keywords": sorted(report_v2.missing_keywords),
                    "recoverable_keywords": sorted(report_v2.recoverable_keywords),
                    "breakdown": {
                        k: v
                        for k, v in breakdown.as_dict().items()
                        # The penalty detail carries prose notes, which are for a
                        # human reading a report and are not part of the contract
                        # the two implementations have to agree on.
                        if k not in {"warnings", "penalty"}
                    },
                    "penalty_total": breakdown.penalty.total,
                },
                # Recorded for context only. The port does not have to reproduce
                # v1; it exists so a reviewer can see what changed and why.
                "v1_overall": report_v1.overall,
            }
        )

    return {
        "note": (
            "Generated by backend/scripts/export_score_fixtures.py. The Python "
            "scorer is the reference implementation. Do not hand-edit."
        ),
        "job": job.model_dump(mode="json"),
        "facts": facts.model_dump(mode="json"),
        "cases": cases,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed fixtures no longer match the scorer.",
    )
    args = parser.parse_args()

    payload = json.dumps(build(), indent=2, sort_keys=True) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"Fixtures missing: {OUT}", file=sys.stderr)
            return 1
        if OUT.read_text() != payload:
            print(
                "Scoring fixtures are stale. The scorer changed but the frozen "
                "answers did not, so the TypeScript port is pinned to the old "
                "behaviour. Run: python scripts/export_score_fixtures.py",
                file=sys.stderr,
            )
            return 1
        print("Scoring fixtures are current.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(payload)
    print(f"Wrote {len(payload):,} bytes to {OUT.relative_to(_ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
