"""Generates the template thumbnails the picker shows.

Run after changing THEMES, the density ladder, or upgrading rendercv:

    python scripts/theme_previews.py

Two decisions worth keeping.

**Built once, not at request time.** Rendering nine PDFs to choose one of them
would cost twenty seconds and the same again on every visit. They are generated
here, written to ``public/themes/`` and committed, and the picker is then a
directory of images. The manifest carries the generation timestamp as a cache
buster so a regenerated thumbnail is not served from a stale cache.

**The thumbnail is a photograph of the real output.** Everything here goes
through the same ``render_pdf`` the download button uses, and the image is that
PDF rasterised. The obvious cheaper route is a hand-built HTML mock of each
template, which is what most editors ship; it drifts from the renderer the
first time a theme changes and then the picker is quietly lying about what you
will get. A thumbnail that cannot be wrong is worth the twenty seconds.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from sample import facts, tailored  # noqa: E402

from atsresume.render.rendercv_adapter import THEMES, render_pdf  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "public" / "themes"
MANIFEST = ROOT / "src" / "lib" / "theme-previews.ts"

# 2x the displayed thumbnail so it stays sharp on a retina screen, and no more:
# nine full-resolution page images is megabytes of payload for a picker.
WIDTH_PX = 420


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    doc = tailored()
    who = facts()

    import pymupdf

    generated: dict[str, str] = {}
    for theme in THEMES:
        print(f"  rendering {theme}...", flush=True)
        result = render_pdf(doc, who, theme=theme)
        with pymupdf.open(stream=result.pdf, filetype="pdf") as pdf:
            page = pdf[0]
            zoom = WIDTH_PX / page.rect.width
            pixmap = page.get_pixmap(matrix=pymupdf.Matrix(zoom, zoom), alpha=False)
            (OUT_DIR / f"{theme}.png").write_bytes(pixmap.tobytes("png"))
        generated[theme] = f"/themes/{theme}.png"
        print(f"    {result.pages} page(s), rung {result.density}")

    stamp = str(int(Path(OUT_DIR / f"{next(iter(THEMES))}.png").stat().st_mtime))
    body = json.dumps(
        {key: f"{path}?v={stamp}" for key, path in generated.items()}, indent=2
    )
    MANIFEST.write_text(
        "// Generated by backend/scripts/theme_previews.py. Do not edit.\n"
        "// Each value is a thumbnail of the real rendered PDF for that template.\n"
        f"export const THEME_PREVIEWS: Record<string, string> = {body};\n",
        encoding="utf-8",
    )
    print(f"\n{len(generated)} thumbnails -> {OUT_DIR}")
    print(f"manifest -> {MANIFEST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
