/**
 * THE ACCEPTANCE TEST.
 *
 * `fixtures/scoring.json` was generated by `backend/scripts/export_score_fixtures.py`
 * from the Python scorer, which is the reference implementation. Every number
 * in it has to come back out of the TypeScript port to one decimal place.
 *
 * The fixture is generated. If a case fails, the port is wrong. Fix the port.
 * Never hand-edit the fixture.
 */

import { describe, expect, it } from 'vitest';
import fixture from './fixtures/scoring.json' with { type: 'json' };

import {
  JobSpecSchema,
  ResumeFactsSchema,
  TailoredResumeSchema,
} from '../src/schema/index.js';
import { computeAtsReport, computeBreakdown } from '../src/scoring/index.js';

const job = JobSpecSchema.parse(fixture.job);
const facts = ResumeFactsSchema.parse(fixture.facts);

interface ExpectedBreakdown {
  overall: number;
  keyword_coverage: number;
  requirement_coverage: number;
  evidence_density: number;
  specificity: number;
  experience_match: number;
  relevance: number;
  quality_gate: number;
  matched_keywords: string[];
  missing_keywords: string[];
  recoverable_keywords: string[];
  keyword_counts: Record<string, number>;
}

interface Expected {
  overall: number;
  penalty_total: number;
  sub_scores: Record<string, number>;
  matched_keywords: string[];
  missing_keywords: string[];
  recoverable_keywords: string[];
  breakdown: ExpectedBreakdown;
}

interface Case {
  name: string;
  tailored: unknown;
  expected: Expected;
}

const cases = fixture.cases as unknown as Case[];

describe('scoring parity with the Python reference', () => {
  it('has the seven generated cases', () => {
    expect(cases).toHaveLength(7);
  });

  it.each(cases.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    const tailored = TailoredResumeSchema.parse(testCase.tailored);
    const report = computeAtsReport(job, facts, tailored);
    const breakdown = computeBreakdown(job, facts, tailored);
    const expected = testCase.expected;

    // --- AtsReport -------------------------------------------------- //
    expect(report.overall).toBeCloseTo(expected.overall, 1);

    for (const [key, value] of Object.entries(expected.sub_scores)) {
      expect(
        report.sub_scores[key as keyof typeof report.sub_scores],
        `sub_scores.${key}`,
      ).toBeCloseTo(value, 1);
    }
    expect(report.sub_scores.penalty).toBeCloseTo(expected.penalty_total, 1);

    // The three keyword arrays. The exporter sorts the AtsReport-level copies
    // (compare `expected.missing_keywords`, alphabetical, against
    // `expected.breakdown.missing_keywords`, job order), so membership is what
    // is asserted here and exact order is asserted on the breakdown below.
    expect([...report.matched_keywords].sort()).toEqual([...expected.matched_keywords].sort());
    expect([...report.missing_keywords].sort()).toEqual([...expected.missing_keywords].sort());
    expect([...report.recoverable_keywords].sort()).toEqual(
      [...expected.recoverable_keywords].sort(),
    );

    // --- ScoreBreakdownV2 ------------------------------------------- //
    const eb = expected.breakdown;
    expect(breakdown.overall, 'breakdown.overall').toBeCloseTo(eb.overall, 1);
    expect(breakdown.keyword_coverage, 'keyword_coverage').toBeCloseTo(eb.keyword_coverage, 1);
    expect(breakdown.requirement_coverage, 'requirement_coverage').toBeCloseTo(
      eb.requirement_coverage,
      1,
    );
    expect(breakdown.evidence_density, 'evidence_density').toBeCloseTo(eb.evidence_density, 1);
    expect(breakdown.specificity, 'specificity').toBeCloseTo(eb.specificity, 1);
    expect(breakdown.experience_match, 'experience_match').toBeCloseTo(eb.experience_match, 1);
    expect(breakdown.relevance, 'relevance').toBeCloseTo(eb.relevance, 1);
    expect(breakdown.quality_gate, 'quality_gate').toBeCloseTo(eb.quality_gate, 1);

    expect(breakdown.matched_keywords).toEqual(eb.matched_keywords);
    expect(breakdown.missing_keywords).toEqual(eb.missing_keywords);
    expect(breakdown.recoverable_keywords).toEqual(eb.recoverable_keywords);

    // Per-term occurrence counts: the saturation and stuffing inputs.
    expect(Object.keys(breakdown.keyword_counts).sort()).toEqual(
      Object.keys(eb.keyword_counts).sort(),
    );
    for (const [term, count] of Object.entries(eb.keyword_counts)) {
      expect(breakdown.keyword_counts[term], `keyword_counts['${term}']`).toBe(count);
    }
  });
});

describe('determinism', () => {
  it('scores the same document identically 50 times', () => {
    const tailored = TailoredResumeSchema.parse(cases[cases.length - 1]!.tailored);
    const first = JSON.stringify(computeAtsReport(job, facts, tailored));
    for (let i = 0; i < 50; i += 1) {
      expect(JSON.stringify(computeAtsReport(job, facts, tailored))).toBe(first);
    }
  });

  it('is unaffected by scoring other documents in between', () => {
    // The vocabulary matcher caches compiled RegExps, and a global RegExp
    // carries `lastIndex`. Interleaving is how that kind of bug shows up.
    const parsed = cases.map((c) => TailoredResumeSchema.parse(c.tailored));
    const baseline = parsed.map((t) => JSON.stringify(computeAtsReport(job, facts, t)));
    for (let round = 0; round < 5; round += 1) {
      parsed.forEach((t, i) => {
        expect(JSON.stringify(computeAtsReport(job, facts, t))).toBe(baseline[i]);
      });
    }
  });

  it('does not mutate its inputs', () => {
    const tailored = TailoredResumeSchema.parse(cases[0]!.tailored);
    const before = JSON.stringify(tailored);
    computeAtsReport(job, facts, tailored);
    computeBreakdown(job, facts, tailored);
    expect(JSON.stringify(tailored)).toBe(before);
  });
});
