"use client";

import { THEME_PREVIEWS } from "@/lib/theme-previews";

/**
 * Choosing a template by looking at it.
 *
 * This was a dropdown of nine names, which asked you to guess what "sb2nov -
 * compact sans" produces and then spend a render finding out. A template is a
 * visual choice and the only honest control for one is the thing itself.
 *
 * Each thumbnail is a rasterised page from the real renderer, generated by
 * backend/scripts/theme_previews.py, so the picker cannot drift away from what
 * the download button produces.
 */

export function TemplatePicker({
  themes,
  value,
  onChange,
}: {
  themes: Record<string, string>;
  value: string;
  onChange: (theme: string) => void;
}) {
  const keys = Object.keys(themes);
  if (keys.length === 0) return null;

  return (
    <div className="border-t border-rule pt-3">
      <p className="label mb-2">Template</p>
      <div className="grid grid-cols-3 gap-1.5">
        {keys.map((key) => {
          const selected = key === value;
          // The label carries a name and a description joined by a dash. The
          // name is all that fits under a thumbnail; the rest is the tooltip.
          const [name] = themes[key].split(" - ");
          return (
            <button
              key={key}
              type="button"
              onClick={() => onChange(key)}
              title={themes[key]}
              aria-pressed={selected}
              className={`group block overflow-hidden border text-left transition-colors ${
                selected
                  ? "border-ink"
                  : "border-rule hover:border-ink-faint"
              }`}
            >
              <span className="block aspect-[210/297] overflow-hidden bg-paper-raised">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={THEME_PREVIEWS[key]}
                  alt=""
                  loading="lazy"
                  draggable={false}
                  className={`h-full w-full object-cover object-top transition-opacity ${
                    selected ? "opacity-100" : "opacity-60 group-hover:opacity-100"
                  }`}
                />
              </span>
              <span
                className={`block truncate px-1 py-0.5 font-mono text-[0.5625rem] uppercase tracking-wider ${
                  selected ? "bg-ink text-paper-raised" : "text-ink-faint"
                }`}
              >
                {name}
              </span>
            </button>
          );
        })}
      </div>
    </div>
  );
}
