/**
 * Shared bits for tier 2.
 *
 * There is no skip guard any more. Tier 2 needed a real Supabase account
 * because the app needed a session; authentication has been removed, so the
 * suite runs for anyone with the dev server up and the `setup` project that
 * signed it in is gone. It stays a separate tier because it is slow, it
 * spends model tokens and it writes rows.
 *
 * The PDF is built rather than committed. A resume fixture checked into a
 * repository is somebody's phone number checked into a repository, which is
 * the same reason `packages/templates/src/fixtures.ts` invents its candidate.
 * This one invents a different candidate on purpose: the name has to be
 * something no fixture in this repository already contains, or the test that
 * matters most here cannot tell the uploaded resume from the sample.
 */

import { test as base, expect } from "@playwright/test";

export const CANDIDATE = {
  name: "Priyanka Raghunathan",
  email: "priyanka.raghunathan@example.com",
  title: "Staff Platform Engineer",
  company: "Calderwood Systems",
};

/** The name of the invented candidate in the repo's own fixtures. */
export const FIXTURE_NAME = "Rohan Iyer";

export const test = base.extend({});

export { expect };

/** A uuid, as the app's own routes validate it. */
export const UUID = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;

/**
 * A single page PDF with real, extractable text.
 *
 * Handwritten rather than generated by a library: the document service parses
 * it with a text extractor, so the content stream has to carry actual Tj
 * operators, and a hundred lines of byte offsets is cheaper than another
 * dependency. Offsets in the xref table are computed, not hardcoded, because
 * a wrong one makes the file unreadable in a way that is very hard to see.
 */
export function resumePdf(): Buffer {
  const lines = [
    CANDIDATE.name,
    CANDIDATE.title,
    `${CANDIDATE.email} | Bengaluru, India`,
    "",
    "SUMMARY",
    "Platform engineer with eight years on payment and settlement systems,",
    "building services in Go and Python on PostgreSQL and Kafka.",
    "",
    "EXPERIENCE",
    `${CANDIDATE.company} - Staff Platform Engineer - 2021 to Present`,
    "Rebuilt the settlement pipeline on Kafka and cut close of day to minutes.",
    "Introduced idempotency keys across the payments API.",
    "Reindexed the ledger database and dropped p99 read latency by an order of magnitude.",
    "",
    "Harbourline Logistics - Backend Engineer - 2018 to 2021",
    "Designed a shipment tracking service handling forty thousand events a minute.",
    "Migrated eleven services off a shared database with no downtime.",
    "",
    "SKILLS",
    "Go, Python, TypeScript, SQL, PostgreSQL, Kafka, Redis, Kubernetes, Terraform",
    "",
    "EDUCATION",
    "College of Engineering, Pune - B.E. Computer Engineering - 2014 to 2018",
  ];

  const escape = (text: string) => text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  let content = "BT\n/F1 11 Tf\n14 TL\n56 780 Td\n";
  for (const line of lines) content += `(${escape(line)}) Tj T*\n`;
  content += "ET\n";

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${Buffer.byteLength(content, "latin1")} >>\nstream\n${content}endstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, "latin1"));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefStart = Buffer.byteLength(pdf, "latin1");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

  return Buffer.from(pdf, "latin1");
}
