// Generated by backend/scripts/theme_previews.py. Do not edit.
// Each value is a thumbnail of the real rendered PDF for that template.
export const THEME_PREVIEWS: Record<string, string> = {
  "engineeringresumes": "/themes/engineeringresumes.png?v=1789631077",
  "classic": "/themes/classic.png?v=1789631077",
  "engineeringclassic": "/themes/engineeringclassic.png?v=1789631077",
  "sb2nov": "/themes/sb2nov.png?v=1789631077",
  "moderncv": "/themes/moderncv.png?v=1789631077",
  "ember": "/themes/ember.png?v=1789631077",
  "harvard": "/themes/harvard.png?v=1789631077",
  "ink": "/themes/ink.png?v=1789631077",
  "opal": "/themes/opal.png?v=1789631077"
};
